version: "3.8"
services:
  grafana:
    image: "grafana/grafana:9.5.12"
    ports:
      - "3000:3000"
    environment:
      GF_PATHS_DATA: /var/lib/grafana
      GF_SECURITY_ADMIN_PASSWORD: admin
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  prometheus:
    image: "prom/prometheus:v2.47.1"
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
    container_name: prometheus
    networks:
      - monitoring

  jmx-kafka101:
    image: "kayademirseda/jmx_exporter:1.0"
    ports:
      - "5556:5556"
    environment:
      CONFIG_YML: "/etc/jmx_exporter/config.yml"
      JVM_OPTS: ${PROMETHEUS_JMX_AGENT_JVM_OPTS}
    volumes:
      - ./etc/jmx_exporter/config_kafka101.yml:/etc/jmx_exporter/config.yml
    container_name: jmx-kafka101
    depends_on:
      - kafka101
    networks:
      - monitoring

  jmx-kafka102:
    image: "kayademirseda/jmx_exporter:1.0"
    ports:
      - "5557:5556"
    environment:
      CONFIG_YML: "/etc/jmx_exporter/config.yml"
      JVM_OPTS: ${PROMETHEUS_JMX_AGENT_JVM_OPTS}

    volumes:
      - ./etc/jmx_exporter/config_kafka102.yml:/etc/jmx_exporter/config.yml
    container_name: jmx-kafka102
    depends_on:
      - kafka102
    networks:
      - monitoring

  jmx-kafka103:
    image: "kayademirseda/jmx_exporter:1.0"
    ports:
      - "5558:5556"
    environment:
      CONFIG_YML: "/etc/jmx_exporter/config.yml"
      JVM_OPTS: ${PROMETHEUS_JMX_AGENT_JVM_OPTS}
    volumes:
      - ./etc/jmx_exporter/config_kafka103.yml:/etc/jmx_exporter/config.yml
    container_name: jmx-kafka103
    depends_on:
      - kafka103
    networks:
      - monitoring

  kafka101:
    image: "kayademirseda/kafka:1.0"
    ports:
      - "19092:9092"
      - "9991:9991"
    container_name: kafka101
    volumes:
    - ./etc/kafka/config/kafka1/server.properties:/kafka/config/server.properties
    - ./etc/kafka/data/kafka1/:/data/kafka/
    environment:
      JMX_PORT: 9991
    deploy:
      resources:
        limits:
          memory: ${KAFKA_BROKER_MEM_LIMIT}
    networks:
      - monitoring

  kafka102:
    image: "kayademirseda/kafka:1.0"
    ports:
      - "29092:9092"
      - "9992:9992"
    container_name: kafka102
    volumes:
    - ./etc/kafka/config/kafka2/server.properties:/kafka/config/server.properties
    - ./etc/kafka/data/kafka2/:/data/kafka/
    environment:
      JMX_PORT: 9992
    deploy:
      resources:
        limits:
          memory: ${KAFKA_BROKER_MEM_LIMIT}
    networks:
      - monitoring

  kafka103:
    image: "kayademirseda/kafka:1.0"
    ports:
      - "39092:9092"
      - "9993:9993"
    container_name: kafka103
    volumes:
    - ./etc/kafka/config/kafka3/server.properties:/kafka/config/server.properties
    - ./etc/kafka/data/kafka3/:/data/kafka/
    environment:
      JMX_PORT: 9993
    deploy:
      resources:
        limits:
          memory: ${KAFKA_BROKER_MEM_LIMIT}
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge
